CATAPP=autocatapp.exe
CATAPPOBJS=autocatapp.obj cat.obj

all: $(CATAPP)

RM=del
CFLAGS=/W3 /EHsc

$(CATAPP): $(CATAPPOBJS)
	$(CXX) $(LFLAGS) /Fe$(CATAPP) $(CATAPPOBJS)

.cc.o:
	$(CXX) $(CFLAGS) $<

clean:
	$(RM) $(CATAPP) $(CATAPPOBJS)
