NUMBERAPP=numberapp.exe
NUMBERAPP_OBJS=numberapp.obj numberutil.obj

all: $(NUMBERAPP)

RM=del
CFLAGS=/W3 /EHsc
$(NUMBERAPP): $(NUMBERAPP_OBJS)
	$(CXX) $(LFLAGS) /Fe$(NUMBERAPP) $(NUMBERAPP_OBJS)

.cc.o:
	$(CXX) $(CFLAGS) $<

clean:
	$(RM) $(NUMBERAPP) $(NUMBERAPP_OBJS)
